name: Update data & upload

on:
  push:
    branches: [ "main", "dev" ]
  schedule:
    - cron: "29 * * * *"

permissions:
  contents: read

env:
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION || '3.11' }}
  ACTOR_IS_OWNER: ${{ github.actor == github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        if: ${{ env.ACTOR_IS_OWNER == 'true' }}
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest poetry
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup pypoetry cache
        uses: actions/cache@v2
        if: ${{ env.ACTOR_IS_OWNER == 'true' }}
        timeout-minutes: 5
        with:
          path: ~/AppData/Local/pypoetry/Cache
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pypoetry-${{ hashFiles('**/requirements.txt') }}${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pypoetry-
      - name: Run Poetry
        run: |
          python -m poetry install

      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Get current week news
        run: |
          mkdir -p 'ecs' &&
          python -m poetry run python get_current_week_news.py > ecs/news.json

      - name: Upload News Artifact
        uses: actions/upload-artifact@v4
        with:
          name: news
          path: ecs/news.json
          retention-days: 1

      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.5.1
        if: ${{ env.ACTOR_IS_OWNER == 'true' }}
        with:
          source-directory: ecs
          destination-github-username: ${{ env.DESTINATION_REPOSITORY_USERNAME || var.DESTINATION_REPOSITORY_USERNAME || 'maxisoft-data' }}
          user-name: ${{ github.actor }}
          user-email: ${{ github.actor }}@users.noreply.github.com
          destination-repository-name: ${{ env.DESTINATION_REPOSITORY_NAME || var.DESTINATION_REPOSITORY_NAME || 'economy-calendar' }}
          create-target-branch-if-needed: ${{ vars.DEPLOY_TO_REPOSITORY_CREATE_TARGET_BRANCH_IF_NEEDED || true }}
          target-branch: ${{ env.DEPLOY_TO_REPOSITORY_TARGET_BRANCH || vars.DEPLOY_TO_REPOSITORY_TARGET_BRANCH || 'main' }}
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
